### ISSUE TITLE
Instruções de utilização incompletas

### ISSUE THREAD

**Issue by marciandreia11** [notaguest404/Tastie-#2]
Não foi possível aceder ao site porque não contém informações suficientes de como instalar o Django, também não tem passos para a utilização do código.

**Comment by notaguest404** [comment]
https://docs.djangoproject.com/en/3.0/topics/install/

**Comment by notaguest404** [comment]
or google: How to install django. It's the first link.

**Comment by notaguest404** [comment]
Readme already updated
